language: r
cache: packages
warnings_are_errors: false

#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel

r_packages:
  - testthat
  
notifications:
  email:
    recipients: tss38@cam.ac.uk
    on_success: change
    on_failure: change

# We don't need latex or pandoc (yet..)
latex: false
pandoc: false
