language: r
cache: packages
warnings_are_errors: false

#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
# Cannot use bioc-devel r:
# Error in install.packages("BiocManager") : unable to install packages
# See: https://travis-ci.community/t/in-r-version-4-0-0-library-path-not-writable/9744/9
#  - bioc-devel

r_packages:
  - testthat
  - covr

notifications:
  email:
    recipients: tss38@cam.ac.uk
    on_success: change
    on_failure: change

# We don't need latex or pandoc (yet..)
latex: false
pandoc: false


# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
