#' ggplot theme for package
#'
#' @description A standard theme to use for plots generated by this package
#'
#' @param base_size base font size, given in pts.
#' @param base_family base font family 
#' @param aspect_square set aspect.ratio to 1
#' @param border include a border
#'
#' @return theme
#' @export
#' 
theme_camprot <- function(base_size=20, base_family='serif',
                          aspect_square=TRUE, border=TRUE){
  
  camprot_theme <- theme_bw(base_size=base_size,
                            base_family=base_family) +
    theme(panel.grid=element_blank(),
          panel.background = element_blank())

  if(aspect_square){
    camprot_theme <- camprot_theme + theme(aspect.ratio=1)
  }
  
  if(!border){
    camprot_theme <- camprot_theme + theme(
      panel.border = element_blank(),
      axis.line = element_line(colour = "black", size=0.5))
  }
  
  camprot_theme
}

#' Generate a colour-blind friendly palette for categorical colour encoding
#'
#' @description For a given number of categories, identify a suitable
#' palette of colours which are colour-blind friendly. Palletes are derived from  
#' \url{http://mkweb.bcgsc.ca/colorblind/palettes.mhtml#page-container}
#'
#' @param n `numeric`. The number of colours required
#'
#' @return Hex codes for colour pallete
#' @export
get_cat_palette <- function(n){
  
  if((n>12 | n<1)) stop('n must be >=1 & <=12')
  
  # colour-blind friendly palettes from:
  # http://mkweb.bcgsc.ca/colorblind/palettes.mhtml#page-container
  
  cbPalette7 <- c("#2271B2", "#f0e442", "#359B73", "#d55e00",
                  "#3DB7E9", "#e69f00", "#F748A5")
  
  cbPalette12 <- c("#9F0162", "#009F81", "#FF5AAF", "#00FCCF",
                   "#8400CD", "#008DF9", "#00C2F9", "#FFB2FD",
                   "#A40122", "#E20134", "#FF6E3A", "#FFC33B")
  
  if(n<=7){
    return(cbPalette7[1:n])
  } else{
    return(cbPalette12[1:n])
  }
}

